### ISSUE TITLE
CAS Consensus code maybe incorrect

### ISSUE THREAD

**Issue by gfredericks** [redolentstoic/redolentstoic.github.io#1]
Hi and thanks for your CAS article! I enjoyed it and learned a lot.

This isn't my expertise, so I say this hesitantly, but the following code for consensus looked wrong to me:

``` c
int decision = -1; 

int propose(int value) {
    while (!CAS(&decision, -1, value));
    return decision;
}
```

My interpretation is that one of the threads will make a successful CAS call, and the rest of them will loop forever since CAS with `-1` will never succeed.

I think it's an easy change to something that works; maybe this?

``` c
int decision = -1; 

int propose(int value) {
    CAS(&decision, -1, value);
    return decision;
}
```

**Comment by redolentstoic** [comment]
Wow! I didn't expect anybody would go through the whole thing.

Yes, you're right! Thank you so much for your comment.  I fixed it and put a small acknowledgment at the end (I hope you are okay with this, otherwise let me know).

Thanks again.

**Comment by gfredericks** [comment]
great, thanks! it's good to know I'm not crazy
